apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.4
    allowUnsupported: false

  dataDirHostPath: /var/lib/rook

  mon:
    count: 3
    allowMultiplePerNode: false

  mgr:
    count: 2
    allowMultiplePerNode: false

  dashboard:
    enabled: true
    ssl: false

  crashCollector:
    disable: false

  storage:
    useAllNodes: true
    useAllDevices: false
    devices:
      - name: "nvme1n1"

  resources:
    mon:
      limits:
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"

    mgr:
      limits:
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"

    osd:
      limits:
        memory: "2Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"

    mds:
      limits:
        memory: "2Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"

  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 60s
      status:
        interval: 60s