apiVersion: batch/v1
kind: Job
metadata:
  name: fio-rwx-fair
spec:
  completions: 3
  parallelism: 3
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: fio-rwx-fair
    spec:
      restartPolicy: Never

      # Force pods onto different nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: fio-rwx-fair
            topologyKey: kubernetes.io/hostname

      containers:
      - name: fio
        image: ljishen/fio
        command: ["fio"]
        args:
          - "--name=rwx-fair"
          - "--directory=/data"
          - "--filename=$(HOSTNAME).dat"
          - "--size=1Gi"
          - "--rw=randwrite"
          - "--bs=4k"
          - "--numjobs=4"
          - "--iodepth=16"
          - "--ioengine=libaio"
          - "--direct=1"
          - "--fsync=1"
          - "--runtime=60"
          - "--time_based"
          - "--group_reporting"

        volumeMounts:
        - name: rwx-vol
          mountPath: /data

      volumes:
      - name: rwx-vol
        persistentVolumeClaim:
          claimName: rwx-pvc


===== pod/fio-rwx-fair-6s67s =====
rwx-fair: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
...
fio-3.6
Starting 4 processes

rwx-fair: (groupid=0, jobs=4): err= 0: pid=10: Tue Feb  3 07:15:18 2026
  write: IOPS=246, BW=985KiB/s (1008kB/s)(57.7MiB/60041msec)
    slat (usec): min=2, max=10744, avg=59.51, stdev=264.47
    clat (msec): min=15, max=523, avg=259.26, stdev=91.97
     lat (msec): min=15, max=523, avg=259.32, stdev=91.97
    clat percentiles (msec):
     |  1.00th=[   33],  5.00th=[   64], 10.00th=[   90], 20.00th=[  190],
     | 30.00th=[  247], 40.00th=[  275], 50.00th=[  292], 60.00th=[  300],
     | 70.00th=[  313], 80.00th=[  326], 90.00th=[  347], 95.00th=[  363],
     | 99.00th=[  393], 99.50th=[  401], 99.90th=[  506], 99.95th=[  514],
     | 99.99th=[  523]
   bw (  KiB/s): min=  127, max=  408, per=24.90%, avg=245.03, stdev=66.30, samples=480
   iops        : min=   31, max=  102, avg=61.10, stdev=16.61, samples=480
  lat (msec)   : 20=0.10%, 50=2.97%, 100=8.69%, 250=18.79%, 500=69.34%
  lat (msec)   : 750=0.12%
  fsync/fdatasync/sync_file_range:
    sync (nsec): min=20, max=614759, avg=273.09, stdev=6759.77
    sync percentiles (nsec):
     |  1.00th=[    22],  5.00th=[    23], 10.00th=[    37], 20.00th=[    44],
     | 30.00th=[    47], 40.00th=[    56], 50.00th=[    87], 60.00th=[   129],
     | 70.00th=[   167], 80.00th=[   223], 90.00th=[   350], 95.00th=[   490],
     | 99.00th=[   772], 99.50th=[   932], 99.90th=[  8896], 99.95th=[ 28288],
     | 99.99th=[403456]
  cpu          : usr=0.09%, sys=0.16%, ctx=12497, majf=0, minf=47
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.2%, 16=199.2%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,14781,0,14721 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=985KiB/s (1008kB/s), 985KiB/s-985KiB/s (1008kB/s-1008kB/s), io=57.7MiB (60.5MB), run=60041-60041msec

===== pod/fio-rwx-fair-868tj =====
rwx-fair: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
...
fio-3.6
Starting 4 processes

rwx-fair: (groupid=0, jobs=4): err= 0: pid=11: Tue Feb  3 07:15:18 2026
  write: IOPS=246, BW=987KiB/s (1011kB/s)(58.1MiB/60201msec)
    slat (usec): min=2, max=19426, avg=110.57, stdev=355.69
    clat (msec): min=11, max=531, avg=258.92, stdev=94.00
     lat (msec): min=11, max=531, avg=259.04, stdev=93.98
    clat percentiles (msec):
     |  1.00th=[   29],  5.00th=[   60], 10.00th=[   81], 20.00th=[  192],
     | 30.00th=[  253], 40.00th=[  279], 50.00th=[  292], 60.00th=[  300],
     | 70.00th=[  313], 80.00th=[  326], 90.00th=[  347], 95.00th=[  359],
     | 99.00th=[  397], 99.50th=[  414], 99.90th=[  518], 99.95th=[  523],
     | 99.99th=[  531]
   bw (  KiB/s): min=  128, max=  568, per=24.96%, avg=246.37, stdev=68.74, samples=480
   iops        : min=   32, max=  142, avg=61.49, stdev=17.18, samples=480
  lat (msec)   : 20=0.26%, 50=3.20%, 100=9.16%, 250=16.55%, 500=70.56%
  lat (msec)   : 750=0.27%
  fsync/fdatasync/sync_file_range:
    sync (nsec): min=25, max=674110, avg=294.72, stdev=7720.19
    sync percentiles (nsec):
     |  1.00th=[    36],  5.00th=[    43], 10.00th=[    46], 20.00th=[    55],
     | 30.00th=[    71], 40.00th=[    98], 50.00th=[   126], 60.00th=[   147],
     | 70.00th=[   175], 80.00th=[   209], 90.00th=[   298], 95.00th=[   406],
     | 99.00th=[   604], 99.50th=[   748], 99.90th=[ 11584], 99.95th=[ 45824],
     | 99.99th=[501760]
  cpu          : usr=0.05%, sys=0.12%, ctx=17558, majf=0, minf=45
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.2%, 16=199.2%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,14861,0,14801 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=987KiB/s (1011kB/s), 987KiB/s-987KiB/s (1011kB/s-1011kB/s), io=58.1MiB (60.9MB), run=60201-60201msec

===== pod/fio-rwx-fair-fg5r5 =====
rwx-fair: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
...
fio-3.6
Starting 4 processes

rwx-fair: (groupid=0, jobs=4): err= 0: pid=10: Tue Feb  3 07:15:18 2026
  write: IOPS=246, BW=985KiB/s (1009kB/s)(57.8MiB/60056msec)
    slat (usec): min=2, max=11855, avg=57.28, stdev=260.09
    clat (msec): min=12, max=574, avg=257.40, stdev=96.75
     lat (msec): min=12, max=574, avg=257.46, stdev=96.75
    clat percentiles (msec):
     |  1.00th=[   34],  5.00th=[   57], 10.00th=[   79], 20.00th=[  182],
     | 30.00th=[  249], 40.00th=[  275], 50.00th=[  292], 60.00th=[  300],
     | 70.00th=[  313], 80.00th=[  326], 90.00th=[  347], 95.00th=[  363],
     | 99.00th=[  409], 99.50th=[  422], 99.90th=[  567], 99.95th=[  575],
     | 99.99th=[  575]
   bw (  KiB/s): min=   31, max=  416, per=25.05%, avg=246.71, stdev=67.10, samples=477
   iops        : min=    7, max=  104, avg=61.52, stdev=16.77, samples=477
  lat (msec)   : 20=0.22%, 50=3.50%, 100=10.22%, 250=16.57%, 500=69.12%
  lat (msec)   : 750=0.37%
  fsync/fdatasync/sync_file_range:
    sync (nsec): min=25, max=599124, avg=330.23, stdev=8137.87
    sync percentiles (nsec):
     |  1.00th=[    40],  5.00th=[    44], 10.00th=[    46], 20.00th=[    51],
     | 30.00th=[    57], 40.00th=[    68], 50.00th=[   104], 60.00th=[   145],
     | 70.00th=[   191], 80.00th=[   251], 90.00th=[   394], 95.00th=[   516],
     | 99.00th=[   820], 99.50th=[   980], 99.90th=[ 10688], 99.95th=[ 30848],
     | 99.99th=[481280]
  cpu          : usr=0.07%, sys=0.14%, ctx=12305, majf=0, minf=49
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.2%, 16=199.2%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,14790,0,14730 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=985KiB/s (1009kB/s), 985KiB/s-985KiB/s (1009kB/s-1009kB/s), io=57.8MiB (60.6MB), run=60056-60056msec


