apiVersion: batch/v1
kind: Job
metadata:
  name: fio-rwx-fair
spec:
  completions: 3
  parallelism: 3
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: fio-rwx-fair
    spec:
      restartPolicy: Never

      # Force pods onto different nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: fio-rwx-fair
            topologyKey: kubernetes.io/hostname

      containers:
      - name: fio
        image: ljishen/fio
        command: ["fio"]
        args:
          - "--name=rwx-fair"
          - "--directory=/data"
          - "--filename=$(HOSTNAME).dat"
          - "--size=1Gi"
          - "--rw=randwrite"
          - "--bs=4k"
          - "--numjobs=4"
          - "--iodepth=16"
          - "--ioengine=libaio"
          - "--direct=1"
          - "--fsync=1"
          - "--runtime=60"
          - "--time_based"
          - "--group_reporting"

        volumeMounts:
        - name: rwx-vol
          mountPath: /data

      volumes:
      - name: rwx-vol
        persistentVolumeClaim:
          claimName: longhorn-rwx-pvc






==============================
RESULTS FROM pod/fio-rwx-fair-4krcp
==============================
rwx-fair: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
...
fio-3.6
Starting 4 processes

rwx-fair: (groupid=0, jobs=4): err= 0: pid=10: Thu Feb  5 07:30:03 2026
  write: IOPS=116, BW=464KiB/s (475kB/s)(27.2MiB/60032msec)
    slat (msec): min=4, max=270, avg=34.42, stdev=24.95
    clat (usec): min=7, max=1088.0k, avg=514899.22, stdev=101218.30
     lat (msec): min=7, max=1096, avg=549.32, stdev=105.12
    clat percentiles (msec):
     |  1.00th=[  351],  5.00th=[  388], 10.00th=[  409], 20.00th=[  435],
     | 30.00th=[  460], 40.00th=[  481], 50.00th=[  502], 60.00th=[  523],
     | 70.00th=[  550], 80.00th=[  584], 90.00th=[  634], 95.00th=[  693],
     | 99.00th=[  852], 99.50th=[  894], 99.90th=[ 1028], 99.95th=[ 1045],
     | 99.99th=[ 1083]
   bw (  KiB/s): min=    8, max=  160, per=24.71%, avg=114.66, stdev=22.91, samples=480
   iops        : min=    2, max=   40, avg=28.49, stdev= 5.75, samples=480
  lat (usec)   : 10=0.01%, 20=0.03%, 50=0.01%
  lat (msec)   : 10=0.01%, 50=0.01%, 100=0.10%, 250=0.20%, 500=48.67%
  lat (msec)   : 750=47.88%, 1000=2.87%
  cpu          : usr=0.07%, sys=0.31%, ctx=24833, majf=0, minf=41
  IO depths    : 1=0.1%, 2=0.1%, 4=0.2%, 8=0.5%, 16=99.1%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=99.9%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,6968,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=464KiB/s (475kB/s), 464KiB/s-464KiB/s (475kB/s-475kB/s), io=27.2MiB (28.5MB), run=60032-60032msec
==============================
RESULTS FROM pod/fio-rwx-fair-8p9xd
==============================
rwx-fair: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
...
fio-3.6
Starting 4 processes

rwx-fair: (groupid=0, jobs=4): err= 0: pid=10: Thu Feb  5 07:30:06 2026
  write: IOPS=115, BW=464KiB/s (475kB/s)(27.2MiB/60019msec)
    slat (msec): min=4, max=338, avg=34.45, stdev=25.09
    clat (usec): min=9, max=937603, avg=515389.45, stdev=96277.12
     lat (msec): min=6, max=956, avg=549.85, stdev=100.03
    clat percentiles (msec):
     |  1.00th=[  342],  5.00th=[  393], 10.00th=[  418], 20.00th=[  443],
     | 30.00th=[  464], 40.00th=[  485], 50.00th=[  506], 60.00th=[  523],
     | 70.00th=[  550], 80.00th=[  584], 90.00th=[  634], 95.00th=[  709],
     | 99.00th=[  802], 99.50th=[  835], 99.90th=[  885], 99.95th=[  885],
     | 99.99th=[  936]
   bw (  KiB/s): min=   16, max=  160, per=24.77%, avg=114.67, stdev=21.26, samples=479
   iops        : min=    4, max=   40, avg=28.50, stdev= 5.35, samples=479
  lat (usec)   : 10=0.03%, 20=0.03%
  lat (msec)   : 10=0.01%, 50=0.07%, 100=0.13%, 250=0.27%, 500=47.71%
  lat (msec)   : 750=49.15%, 1000=2.59%
  cpu          : usr=0.07%, sys=0.28%, ctx=24976, majf=0, minf=39
  IO depths    : 1=0.1%, 2=0.1%, 4=0.2%, 8=0.5%, 16=99.1%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=99.9%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,6958,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=464KiB/s (475kB/s), 464KiB/s-464KiB/s (475kB/s-475kB/s), io=27.2MiB (28.5MB), run=60019-60019msec
==============================
RESULTS FROM pod/fio-rwx-fair-c7bpq
==============================
rwx-fair: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
...
fio-3.6
Starting 4 processes

rwx-fair: (groupid=0, jobs=4): err= 0: pid=10: Thu Feb  5 07:30:11 2026
  write: IOPS=125, BW=504KiB/s (516kB/s)(29.5MiB/60024msec)
    slat (msec): min=4, max=154, avg=31.70, stdev=18.62
    clat (usec): min=8, max=804365, avg=472976.94, stdev=79489.73
     lat (msec): min=5, max=867, avg=504.68, stdev=82.83
    clat percentiles (msec):
     |  1.00th=[  313],  5.00th=[  368], 10.00th=[  388], 20.00th=[  409],
     | 30.00th=[  430], 40.00th=[  447], 50.00th=[  468], 60.00th=[  485],
     | 70.00th=[  506], 80.00th=[  531], 90.00th=[  575], 95.00th=[  617],
     | 99.00th=[  684], 99.50th=[  709], 99.90th=[  785], 99.95th=[  802],
     | 99.99th=[  802]
   bw (  KiB/s): min=   71, max=  184, per=25.04%, avg=125.94, stdev=19.64, samples=476
   iops        : min=   17, max=   46, avg=31.41, stdev= 4.90, samples=476
  lat (usec)   : 10=0.04%, 20=0.01%
  lat (msec)   : 10=0.01%, 50=0.08%, 100=0.09%, 250=0.32%, 500=66.85%
  lat (msec)   : 750=32.38%, 1000=0.21%
  cpu          : usr=0.06%, sys=0.26%, ctx=25044, majf=0, minf=40
  IO depths    : 1=0.1%, 2=0.1%, 4=0.2%, 8=0.4%, 16=99.2%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=99.9%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,7563,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=504KiB/s (516kB/s), 504KiB/s-504KiB/s (516kB/s-516kB/s), io=29.5MiB (30.0MB), run=60024-60024msec